# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

platform :osx, '10.13'

target 'ReadSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReadSwift
  pod 'SourceKittenFramework', '~> 0.21.0'
  
end